services:
  ghost:
    image: ghost:5-alpine
    ports:
      - "8083:2368"
    environment:
      # Ép Ghost nhận diện đúng URL để không bị lỗi từ chối kết nối
      url: http://13.210.91.137:8083
      database__client: sqlite3